### ISSUE TITLE
WebApp in framwork folder not loading correctly.

### ISSUE THREAD

**Issue by Drakesinger** [Arnianor/CVGenerator#3]
### Steps
1. Install the webapp with composer <pre>composer install</pre>
2. Configure ngix to point to <pre>CVGenerator/framework/public</pre>
3. Restart ngix
### Output

When loading the url the following appears:

<pre> Oups, something went wrong </pre>

**Comment by Drakesinger** [comment]
Forgot the .env file.
Solved.

**Comment by greut** [comment]
:+1:
